version: '3'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://Shubhi:Nims%4077@cluster0.7hopfg9.mongodb.net/taskdb?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
