name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Server Dependencies
      working-directory: ./server
      run: npm install

    - name: Install Client Dependencies
      working-directory: ./client
      run: npm install --legacy-peer-deps

    - name: Build React App
      working-directory: ./client
      run: ./node_modules/.bin/react-scripts build


    - name: Lint Client Code (SAST)
      working-directory: ./client
      run: npx eslint src --ext .js,.jsx || true


    - name: Run npm audit (server)
      working-directory: ./server
      run: npm audit --audit-level=high || true

    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Trivy Scan (client)
      run: trivy fs ./client --severity HIGH,CRITICAL --exit-code 0

    - name: Trivy Scan (server)
      run: trivy fs ./server --severity HIGH,CRITICAL --exit-code 0

