name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Server Dependencies
      working-directory: ./server
      run: npm install

    - name: Install Client Dependencies
      working-directory: ./client
      run: npm install

    - name: Lint Client Code (SAST)
      working-directory: ./client
      run: npx eslint src --ext .js,.jsx || true

    - name: Build React App
      working-directory: ./client
      run: npm run build

